logging:
  file: target/application.log
  level:
    root: INFO
    com.luhuiguo: INFO
spring:
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./target/h2db/db/demo;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true

application:
  logging:
    logstash:
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
